# Generated by Django 5.2.17 on 2026-09-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_housecount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(help_text='Ej: Dormitorio Principal, Baño Completo, Cocina', max_length=100)),
                ('dimensiones', models.CharField(help_text='Ej: 3m x 4m (12 m²)', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Módulo de Habitación',
                'verbose_name_plural': 'Módulos de Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cemento Polpaico 25kg, Plancha Volcanita 10mm', max_length=150)),
                ('coste', models.BigIntegerField(help_text='Costo unitario del material en CLP')),
                ('dimensiones', models.CharField(blank=True, help_text='Ej: 1.20m x 2.40m, 6 metros, etc.', max_length=100, null=True)),
                ('unidad_medida', models.CharField(default='Unidad', help_text='Ej: Saco, Plancha, Tira, m²', max_length=50)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MaterialHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad requerida de este material')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_materiales', to='app_housecount.habitacion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_habitaciones', to='app_housecount.material')),
            ],
            options={
                'verbose_name': 'Material de Habitación',
                'verbose_name_plural': 'Materiales de Habitaciones',
                'unique_together': {('habitacion', 'material')},
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='materiales',
            field=models.ManyToManyField(help_text='Materiales necesarios para construir esta habitación', related_name='habitaciones', through='app_housecount.MaterialHabitacion', to='app_housecount.material'),
        ),
    ]
