# Generated by Django 5.2.17 on 2026-09-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('metros_cuadrados', models.IntegerField(help_text='Superficie en m²')),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('precio', models.BigIntegerField(help_text='Precio en CLP')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modelos/')),
            ],
            options={
                'verbose_name': 'Modelo de Casa',
                'verbose_name_plural': 'Modelos de Casas',
            },
        ),
    ]
