# Generated by Django 5.2.17 on 2026-09-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_housecount', '0002_habitacion_material_materialhabitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='archivo_3d',
            field=models.FileField(blank=True, help_text='Archivo .glb para el módulo prefabricado', null=True, upload_to='modelos_3d/habitaciones/'),
        ),
        migrations.AddField(
            model_name='material',
            name='archivo_3d',
            field=models.FileField(blank=True, help_text='Archivo .glb para el modelo 3D', null=True, upload_to='modelos_3d/materiales/'),
        ),
    ]
