# Generated by Django 5.2.17 on 2026-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_housecount', '0004_proyecto3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_habitaciones/'),
        ),
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_materiales/'),
        ),
    ]
