# Generated by Django 5.2.17 on 2026-10-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_housecount', '0006_categoriamaterial_material_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto3d',
            name='area_cuadrada',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Superficie total estimada', max_digits=8),
        ),
        migrations.AddField(
            model_name='proyecto3d',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto3d',
            name='imagen_captura',
            field=models.ImageField(blank=True, help_text='Miniatura del diseño', null=True, upload_to='capturas_proyectos/'),
        ),
        migrations.AlterField(
            model_name='proyecto3d',
            name='datos_camara',
            field=models.JSONField(help_text='JSON con posición y target de la cámara'),
        ),
        migrations.AlterField(
            model_name='proyecto3d',
            name='datos_escena',
            field=models.JSONField(help_text='JSON con objetos y posiciones'),
        ),
    ]
